# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c57db7720b6e18a5368837b167be20344988c89a0c5882abefd9eaa24677d025286791aa776a1df9b00cf7796d3f3c266a04a50df9406037b132cb0e656ef20

test:
  secret_key_base: b7471ee08f52b1297cfdf49f38bd0fa87f73e232293718a55777adb60230acb96fed0b599a3b20a7c7fda89917b82abf81a31a8b553974ba926c177d568ecd65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
